# Generated by Django 4.2.2 on 2023-10-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('proposalSummary', models.TextField(max_length=1500)),
                ('projectPlanning', models.TextField(max_length=2200)),
                ('financing', models.TextField(max_length=2550)),
                ('contactName', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhoneNo', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.proposal')),
            ],
        ),
    ]
